#!/bin/bash


D=$(realpath "$(dirname "$0")")
DOTDIR=".dotdir"

# Link files and directories in the same structure as they appear here into the
# appropriate target of the same structure.
#
# If a source directory contains the special file $DOTDIR, then the directory
# is linked as is. Otherwise, it is recursively traversed and it's files or
# directories are linked.
#
# Currently this supports only two top level directories: home, and root which
# map to $HOME and /, respectively.
linkDir() {
  root=$1
  for fn in "$root"/{,.}*; do
    bn="$(basename "$fn")"
    if [ "$bn" = '.' ] || [ "$bn" = '..' ]; then
      continue
    fi
    if [ -d "$fn" ] && [ ! -f "$fn/$DOTDIR" ]; then
      linkDir "$fn"
    else
      src="$D/$fn"
      dst=$(echo "$fn" \
        | sed 's@^home@'"$HOME"'@' \
        | sed 's/^root/\//' \
      )
      # If the dst already links to our src, then we don't need to link again.
      if [ "$(realpath "$src")" = "$(realpath -m "$dst")" ]; then
        continue
      fi
      # Make the necessary directory, since linking will fail otherwise.
      dn="$(dirname "$dst")"
      if [ ! -d "$dn" ]; then
        mkdir -p "$dn"
      fi
      # If it's a dead link, or doesn't yet exist then just replace it.
      if [ ! -e "$dst" ]; then
        rm -f "$dst"
        ln -s "$src" "$dst"
      else
        echo target already exists "$src -> $dst"
      fi
    fi
  done
}

linkDir home
