[theme]
name = "plain"
[theme.overrides]
separator = "-"

[icons]
name = "none"

[[block]]
block = "sound"

[[block]]
block = "cpu"
interval = 1
format = "{utilization}%"

[[block]]
block = "memory"
format_mem = "{Mup}%"

# [[block]]
# block = "disk_space"
# info_type = "available"
# unit = "GB"

# [[block]]
# block = "github"
# format = "{total}|{author}|{comment}|{mention}|{review_requested}"

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
# format = "{ssid} {ip}"
# format = ""
ip = true
speed_up = false
speed_down = false
# graph_up = true
# graph_down = true
# signal_strength = true
# speed_up = false
interval = 1
# use_bits = false
#
[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 1
format = "%a %m/%d %r"

[[block]]
block = "uptime"
