prompt_order = [
    "username",
    "hostname",
    # "python"
    # "kubernetes",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "custom.git_test",
    "custom.git_stash",
    "custom.git_commits",
    # "memory_usage",
    # "env_var",
    "cmd_duration",
    "line_break",
    "jobs",
    # "battery",
    # "time",
    "character",
]

[character]
symbol = "$"

[jobs]
symbol = "+"

[git_branch]
symbol = ""

[custom.git_stash]
command = "stash-summary"
prefix = "stash "
when = 'git rev-parse --is-inside-work-tree && [ -n "$(git stash list)" ]'

[custom.git_commits]
prefix = "commits "
command = "git log --oneline $(git merge-base master HEAD)..HEAD | wc -l"
when = "git rev-parse --is-inside-work-tree"

