format = """\
$hostname\
$directory\
$git_branch$git_state$git_status\
$python \
$cmd_duration\
$line_break\
$status\
$jobs$character\
"""

[python]
format = '[($virtualenv)]($style)'

[hostname]
ssh_only = false
style = "blue"

[directory]
style = "bold green"

[git_branch]
style = "purple"
symbol = ""

[git_status]
style = "dimmed"

[cmd_duration]
min_time = 500

[jobs]
symbol = "+"
style = "bold blue"

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"


[custom.git_stash]
command = "stash-summary"
prefix = "stash "
when = 'git rev-parse --is-inside-work-tree && [ -n "$(git stash list)" ]'

[custom.git_commits]
prefix = "commits "
command = "git log --oneline $(git merge-base master HEAD)..HEAD | wc -l"
when = "git rev-parse --is-inside-work-tree"

